export default 
    [
  // {
  //   "id": 1,
  //   "landTypeCode": 1,
  //   "landType": "Land for cultivation",
  //   "landSubType1": "Assessed",
  //   "landSubType2": "Occupied (unalienated)",
  //   "landSubType3": "Occupant Class - 1",
  //   "landTypeMarathi": "लागवडीकरीता जमीन",
  //   "landSubType1Marathi": "आकारी जमीन",
  //   "landSubType2Marathi": "भोगवट्याीची (बिनदुमला) जमीन",
  //   "landSubType3Marathi": "भोगवटादार वर्ग १",
  //   "landTypeWithSubtype": "Land for cultivation-Assessed/Occupied (unalienated)/Occupant Class - 1",
  //   "landTypeWithSubtypeMarathi": "लागवडीकरीता जमीन-आकारी जमीन/भोगवट्याीची (बिनदुमला) जमीन/भोगवटादार वर्ग १"
  // },
  {
    "id": 2,
    "landTypeCode": 2,
    "landType": "Land for cultivation",
    "landSubType1": "Assessed",
    "landSubType2": "Occupied (unalienated)",
    "landSubType3": "Occupant Class - 2",
    "landTypeMarathi": "लागवडीकरीता जमीन",
    "landSubType1Marathi": "आकारी जमीन",
    "landSubType2Marathi": "भोगवट्याीची (बिनदुमला) जमीन",
    "landSubType3Marathi": "भोगवटादार वर्ग २",
    "landTypeWithSubtype": "Land for cultivation-Assessed/Occupied (unalienated)/Occupant Class - 2",
    "landTypeWithSubtypeMarathi": "लागवडीकरीता जमीन-आकारी जमीन/भोगवट्याीची (बिनदुमला) जमीन/भोगवटादार वर्ग २"
  },
  {
    "id": 3,
    "landTypeCode": 3,
    "landType": "Land for cultivation",
    "landSubType1": "Assessed",
    "landSubType2": "Occupied (unalienated)",
    "landSubType3": "Government Lessees",
    "landTypeMarathi": "लागवडीकरीता जमीन",
    "landSubType1Marathi": "आकारी जमीन",
    "landSubType2Marathi": "भोगवट्याीची (बिनदुमला) जमीन",
    "landSubType3Marathi": "शासकीय पट्टेरदार",
    "landTypeWithSubtype": "Land for cultivation-Assessed/Occupied (unalienated)/Government Lessees",
    "landTypeWithSubtypeMarathi": "लागवडीकरीता जमीन-आकारी जमीन/भोगवट्याीची (बिनदुमला) जमीन/शासकीय पट्टेरदार"
  },
  // {
  //   "id": 4,
  //   "landTypeCode": 4,
  //   "landType": "Land for cultivation",
  //   "landSubType1": "Assessed",
  //   "landSubType2": "Unoccupied",
  //   "landSubType3": null,
  //   "landTypeMarathi": "लागवडीकरीता जमीन",
  //   "landSubType1Marathi": "आकारी जमीन",
  //   "landSubType2Marathi": "बिनभोगवट्याची जमीन ",
  //   "landSubType3Marathi": null,
  //   "landTypeWithSubtype": "Land for cultivation-Assessed/Unoccupied",
  //   "landTypeWithSubtypeMarathi": "लागवडीकरीता जमीन-आकारी जमीन/बिनभोगवट्याची जमीन "
  // },
  {
    "id": 5,
    "landTypeCode": 5,
    "landType": "Land for cultivation",
    "landSubType1": "Assessed",
    "landSubType2": "Land free or reduced by special agreement",
    "landSubType3": null,
    "landTypeMarathi": "लागवडीकरीता जमीन",
    "landSubType1Marathi": "आकारी जमीन",
    "landSubType2Marathi": "विशेष करारान्वरये महसूल माफ \r\nकिंवा पुनर्वसनासाठी संपादीत किंवा कम आकारी जमीन\r\n",
    "landSubType3Marathi": null,
    "landTypeWithSubtype": "Land for cultivation-Assessed/Land free or reduced by special agreement",
    "landTypeWithSubtypeMarathi": "लागवडीकरीता जमीन-आकारी जमीन/विशेष करारान्वरये महसूल माफ \r\nकिंवा पुनर्वसनासाठी संपादीत किंवा कम आकारी जमीन\r\n"
  },
  {
    "id": 6,
    "landTypeCode": 6,
    "landType": "Land for cultivation",
    "landSubType1": "Assessed",
    "landSubType2": "Alienated",
    "landSubType3": null,
    "landTypeMarathi": "लागवडीकरीता जमीन",
    "landSubType1Marathi": "आकारी जमीन",
    "landSubType2Marathi": "दुमाला जमीन",
    "landSubType3Marathi": null,
    "landTypeWithSubtype": "Land for cultivation-Assessed/Alienated",
    "landTypeWithSubtypeMarathi": "लागवडीकरीता जमीन-आकारी जमीन/दुमाला जमीन"
  },
  {
    "id": 7,
    "landTypeCode": 7,
    "landType": "Land for cultivation",
    "landSubType1": "Unassessed",
    "landSubType2": "Unoccupied",
    "landSubType3": null,
    "landTypeMarathi": "लागवडीकरीता जमीन",
    "landSubType1Marathi": "बिन आकारी जमीन ",
    "landSubType2Marathi": "बिनभोगवट्याची जमीन ",
    "landSubType3Marathi": null,
    "landTypeWithSubtype": "Land for cultivation-Unassessed/Unoccupied",
    "landTypeWithSubtypeMarathi": "लागवडीकरीता जमीन-बिन आकारी जमीन /बिनभोगवट्याची जमीन "
  },
  {
    "id": 8,
    "landTypeCode": 8,
    "landType": "Land for cultivation",
    "landSubType1": "Unassessed",
    "landSubType2": "Assigned for special use (eg. agricultural farm, rice breeding centre)",
    "landSubType3": null,
    "landTypeMarathi": "लागवडीकरीता जमीन",
    "landSubType1Marathi": "बिन आकारी जमीन ",
    "landSubType2Marathi": " विशेष वापरासाठी नेमून दिलेली जमीन\r\n(उदा. कृषी क्षेत्र, भात पैदास केंद्र इ.)\r\n",
    "landSubType3Marathi": null,
    "landTypeWithSubtype": "Land for cultivation-Unassessed/Assigned for special use (eg. agricultural farm, rice breeding centre)",
    "landTypeWithSubtypeMarathi": "लागवडीकरीता जमीन-बिन आकारी जमीन / विशेष वापरासाठी नेमून दिलेली जमीन\r\n(उदा. कृषी क्षेत्र, भात पैदास केंद्र इ.)\r\n"
  },
  {
    "id": 9,
    "landTypeCode": 9,
    "landType": "Land not available for cultivation",
    "landSubType1": "Uncultivated",
    "landSubType2": "Pot Kharaba",
    "landSubType3": null,
    "landTypeMarathi": "लागवडीसाठी अनुपलब्धक जमीन",
    "landSubType1Marathi": "लागवड अयोग्य",
    "landSubType2Marathi": "पोट खराब",
    "landSubType3Marathi": null,
    "landTypeWithSubtype": "Land not available for cultivation-Uncultivated/Pot Kharaba",
    "landTypeWithSubtypeMarathi": "लागवडीसाठी अनुपलब्धक जमीन-लागवड अयोग्य/पोट खराब"
  },
  {
    "id": 10,
    "landTypeCode": 10,
    "landType": "Land not available for cultivation",
    "landSubType1": "Uncultivated",
    "landSubType2": "Rivers and Nallas",
    "landSubType3": null,
    "landTypeMarathi": "लागवडीसाठी अनुपलब्धक जमीन",
    "landSubType1Marathi": "लागवड अयोग्य",
    "landSubType2Marathi": " नद्या आणि\r\nनाले\r\n",
    "landSubType3Marathi": null,
    "landTypeWithSubtype": "Land not available for cultivation-Uncultivated/Rivers and Nallas",
    "landTypeWithSubtypeMarathi": "लागवडीसाठी अनुपलब्धक जमीन-लागवड अयोग्य/ नद्या आणि\r\nनाले\r\n"
  },
  {
    "id": 11,
    "landTypeCode": 11,
    "landType": "Land not available for cultivation",
    "landSubType1": "Assigned for public and special uses",
    "landSubType2": "Forest",
    "landSubType3": null,
    "landTypeMarathi": "लागवडीसाठी अनुपलब्धक जमीन",
    "landSubType1Marathi": "सार्वजनिक किंवा विशेष वापरासाठी नेमून दिलेली",
    "landSubType2Marathi": "वन",
    "landSubType3Marathi": null,
    "landTypeWithSubtype": "Land not available for cultivation-Assigned for public and special uses/Forest",
    "landTypeWithSubtypeMarathi": "लागवडीसाठी अनुपलब्धक जमीन-सार्वजनिक किंवा विशेष वापरासाठी नेमून दिलेली/वन"
  },
  {
    "id": 12,
    "landTypeCode": 12,
    "landType": "Land not available for cultivation",
    "landSubType1": "Assigned for public and special uses",
    "landSubType2": "Kuran",
    "landSubType3": null,
    "landTypeMarathi": "लागवडीसाठी अनुपलब्धक जमीन",
    "landSubType1Marathi": "सार्वजनिक किंवा विशेष वापरासाठी नेमून दिलेली",
    "landSubType2Marathi": "कुरण",
    "landSubType3Marathi": null,
    "landTypeWithSubtype": "Land not available for cultivation-Assigned for public and special uses/Kuran",
    "landTypeWithSubtypeMarathi": "लागवडीसाठी अनुपलब्धक जमीन-सार्वजनिक किंवा विशेष वापरासाठी नेमून दिलेली/कुरण"
  },
  {
    "id": 13,
    "landTypeCode": 13,
    "landType": "Land not available for cultivation",
    "landSubType1": "Assigned for public and special uses",
    "landSubType2": "Free pasture/cattle land",
    "landSubType3": null,
    "landTypeMarathi": "लागवडीसाठी अनुपलब्धक जमीन",
    "landSubType1Marathi": "सार्वजनिक किंवा विशेष वापरासाठी नेमून दिलेली",
    "landSubType2Marathi": "नि:शुल्क गायरान, गुरांचा तळ",
    "landSubType3Marathi": null,
    "landTypeWithSubtype": "Land not available for cultivation-Assigned for public and special uses/Free pasture/cattle land",
    "landTypeWithSubtypeMarathi": "लागवडीसाठी अनुपलब्धक जमीन-सार्वजनिक किंवा विशेष वापरासाठी नेमून दिलेली/नि:शुल्क गायरान, गुरांचा तळ"
  },
  {
    "id": 14,
    "landTypeCode": 14,
    "landType": "Land not available for cultivation",
    "landSubType1": "Assigned for public and special uses",
    "landSubType2": "Village site",
    "landSubType3": null,
    "landTypeMarathi": "लागवडीसाठी अनुपलब्धक जमीन",
    "landSubType1Marathi": "सार्वजनिक किंवा विशेष वापरासाठी नेमून दिलेली",
    "landSubType2Marathi": "गावठाण",
    "landSubType3Marathi": null,
    "landTypeWithSubtype": "Land not available for cultivation-Assigned for public and special uses/Village site",
    "landTypeWithSubtypeMarathi": "लागवडीसाठी अनुपलब्धक जमीन-सार्वजनिक किंवा विशेष वापरासाठी नेमून दिलेली/गावठाण"
  },
  {
    "id": 15,
    "landTypeCode": 15,
    "landType": "Land not available for cultivation",
    "landSubType1": "Assigned for public and special uses",
    "landSubType2": "Tank",
    "landSubType3": null,
    "landTypeMarathi": "लागवडीसाठी अनुपलब्धक जमीन",
    "landSubType1Marathi": "सार्वजनिक किंवा विशेष वापरासाठी नेमून दिलेली",
    "landSubType2Marathi": " तलाव",
    "landSubType3Marathi": null,
    "landTypeWithSubtype": "Land not available for cultivation-Assigned for public and special uses/Tank",
    "landTypeWithSubtypeMarathi": "लागवडीसाठी अनुपलब्धक जमीन-सार्वजनिक किंवा विशेष वापरासाठी नेमून दिलेली/ तलाव"
  },
  {
    "id": 16,
    "landTypeCode": 16,
    "landType": "Land not available for cultivation",
    "landSubType1": "Assigned for public and special uses",
    "landSubType2": "Burial Ground",
    "landSubType3": null,
    "landTypeMarathi": "लागवडीसाठी अनुपलब्धक जमीन",
    "landSubType1Marathi": "सार्वजनिक किंवा विशेष वापरासाठी नेमून दिलेली",
    "landSubType2Marathi": "स्मशान भूमी",
    "landSubType3Marathi": null,
    "landTypeWithSubtype": "Land not available for cultivation-Assigned for public and special uses/Burial Ground",
    "landTypeWithSubtypeMarathi": "लागवडीसाठी अनुपलब्धक जमीन-सार्वजनिक किंवा विशेष वापरासाठी नेमून दिलेली/स्मशान भूमी"
  },
  {
    "id": 17,
    "landTypeCode": 17,
    "landType": "Land not available for cultivation",
    "landSubType1": "Assigned for public and special uses",
    "landSubType2": "Railways",
    "landSubType3": null,
    "landTypeMarathi": "लागवडीसाठी अनुपलब्धक जमीन",
    "landSubType1Marathi": "सार्वजनिक किंवा विशेष वापरासाठी नेमून दिलेली",
    "landSubType2Marathi": " रेल्वे मार्ग ",
    "landSubType3Marathi": null,
    "landTypeWithSubtype": "Land not available for cultivation-Assigned for public and special uses/Railways",
    "landTypeWithSubtypeMarathi": "लागवडीसाठी अनुपलब्धक जमीन-सार्वजनिक किंवा विशेष वापरासाठी नेमून दिलेली/ रेल्वे मार्ग "
  },
  {
    "id": 18,
    "landTypeCode": 18,
    "landType": "Land not available for cultivation",
    "landSubType1": "Assigned for public and special uses",
    "landSubType2": "Potkharaba assigned for roads, water courses etc.",
    "landSubType3": null,
    "landTypeMarathi": "लागवडीसाठी अनुपलब्धक जमीन",
    "landSubType1Marathi": "सार्वजनिक किंवा विशेष वापरासाठी नेमून दिलेली",
    "landSubType2Marathi": "पाण्याचे पाट इत्या्दी करता असलेली पो.ख.",
    "landSubType3Marathi": null,
    "landTypeWithSubtype": "Land not available for cultivation-Assigned for public and special uses/Potkharaba assigned for roads, water courses etc.",
    "landTypeWithSubtypeMarathi": "लागवडीसाठी अनुपलब्धक जमीन-सार्वजनिक किंवा विशेष वापरासाठी नेमून दिलेली/पाण्याचे पाट इत्या्दी करता असलेली पो.ख."
  },
  {
    "id": 19,
    "landTypeCode": 19,
    "landType": "Land not available for cultivation",
    "landSubType1": "Assigned for public and special uses",
    "landSubType2": "Roads and Paths",
    "landSubType3": null,
    "landTypeMarathi": "लागवडीसाठी अनुपलब्धक जमीन",
    "landSubType1Marathi": "सार्वजनिक किंवा विशेष वापरासाठी नेमून दिलेली",
    "landSubType2Marathi": "रस्ते व मार्ग",
    "landSubType3Marathi": null,
    "landTypeWithSubtype": "Land not available for cultivation-Assigned for public and special uses/Roads and Paths",
    "landTypeWithSubtypeMarathi": "लागवडीसाठी अनुपलब्धक जमीन-सार्वजनिक किंवा विशेष वापरासाठी नेमून दिलेली/रस्ते व मार्ग"
  },
  {
    "id": 20,
    "landTypeCode": 20,
    "landType": "Land not available for cultivation",
    "landSubType1": "Assigned for public and special uses",
    "landSubType2": "Pipelines, canals and drains",
    "landSubType3": null,
    "landTypeMarathi": "लागवडीसाठी अनुपलब्धक जमीन",
    "landSubType1Marathi": "सार्वजनिक किंवा विशेष वापरासाठी नेमून दिलेली",
    "landSubType2Marathi": "नळमार्ग, कालवे, चर इत्यादी",
    "landSubType3Marathi": null,
    "landTypeWithSubtype": "Land not available for cultivation-Assigned for public and special uses/Pipelines, canals and drains",
    "landTypeWithSubtypeMarathi": "लागवडीसाठी अनुपलब्धक जमीन-सार्वजनिक किंवा विशेष वापरासाठी नेमून दिलेली/नळमार्ग, कालवे, चर इत्यादी"
  },
  {
    "id": 21,
    "landTypeCode": 21,
    "landType": "Land not available for cultivation",
    "landSubType1": "Assigned for public and special uses",
    "landSubType2": "Cantonment Lands (military camp, shooting range etc.",
    "landSubType3": null,
    "landTypeMarathi": "लागवडीसाठी अनुपलब्धक जमीन",
    "landSubType1Marathi": "सार्वजनिक किंवा विशेष वापरासाठी नेमून दिलेली",
    "landSubType2Marathi": "कटक (कॉन्टनन्मेंाट)  क्षेत्रातील जमिनी\r\n(सैनिकी छावणी, गोळीबार क्षेत्र इत्यादी)\r\n",
    "landSubType3Marathi": null,
    "landTypeWithSubtype": "Land not available for cultivation-Assigned for public and special uses/Cantonment Lands (military camp, shooting range etc.",
    "landTypeWithSubtypeMarathi": "लागवडीसाठी अनुपलब्धक जमीन-सार्वजनिक किंवा विशेष वापरासाठी नेमून दिलेली/कटक (कॉन्टनन्मेंाट)  क्षेत्रातील जमिनी\r\n(सैनिकी छावणी, गोळीबार क्षेत्र इत्यादी)\r\n"
  },
  {
    "id": 22,
    "landTypeCode": 22,
    "landType": "Land not available for cultivation",
    "landSubType1": "Assigned for public and special uses",
    "landSubType2": "Schools",
    "landSubType3": null,
    "landTypeMarathi": "लागवडीसाठी अनुपलब्धक जमीन",
    "landSubType1Marathi": "सार्वजनिक किंवा विशेष वापरासाठी नेमून दिलेली",
    "landSubType2Marathi": "शाळा",
    "landSubType3Marathi": null,
    "landTypeWithSubtype": "Land not available for cultivation-Assigned for public and special uses/Schools",
    "landTypeWithSubtypeMarathi": "लागवडीसाठी अनुपलब्धक जमीन-सार्वजनिक किंवा विशेष वापरासाठी नेमून दिलेली/शाळा"
  },
  {
    "id": 23,
    "landTypeCode": 23,
    "landType": "Land not available for cultivation",
    "landSubType1": "Assigned for public and special uses",
    "landSubType2": "Dharamshalas",
    "landSubType3": null,
    "landTypeMarathi": "लागवडीसाठी अनुपलब्धक जमीन",
    "landSubType1Marathi": "सार्वजनिक किंवा विशेष वापरासाठी नेमून दिलेली",
    "landSubType2Marathi": "धर्मशाळा",
    "landSubType3Marathi": null,
    "landTypeWithSubtype": "Land not available for cultivation-Assigned for public and special uses/Dharamshalas",
    "landTypeWithSubtypeMarathi": "लागवडीसाठी अनुपलब्धक जमीन-सार्वजनिक किंवा विशेष वापरासाठी नेमून दिलेली/धर्मशाळा"
  },
  {
    "id": 24,
    "landTypeCode": 24,
    "landType": "Land not available for cultivation",
    "landSubType1": "Leased or granted out of S. No. for NA uses including alienation of Class VII",
    "landSubType2": null,
    "landSubType3": null,
    "landTypeMarathi": "लागवडीसाठी अनुपलब्धक जमीन",
    "landSubType1Marathi": "(वापरात बदल केल्यालनंतर), पट्या्ने दिलेली प्रदान केलेली शासकीय जमीन (इनाम वर्ग सात सह)",
    "landSubType2Marathi": null,
    "landSubType3Marathi": null,
    "landTypeWithSubtype": "Land not available for cultivation-Leased or granted out of S. No. for NA uses including alienation of Class VII",
    "landTypeWithSubtypeMarathi": "लागवडीसाठी अनुपलब्धक जमीन-(वापरात बदल केल्यालनंतर), पट्या्ने दिलेली प्रदान केलेली शासकीय जमीन (इनाम वर्ग सात सह)"
  }
]
